FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# viaDDSdemo1

viaDDSdemo1 is an ViaSat Data Delivery service API allowing consumers to request data collection from various antenna sites around the world.


## Reservation Collection [/reservations/{user_id}]

A colleciton of all reservations for a particular user

+ Parameters
    + user_id (string) - ID of the dds user in the form of an string

+ Model (application/json)

    +   Body
    
            {
                "id": {task_id},
                "site":"mySite",
                "start time": 2016 021 01:27:45,
                "stop time":2016 021 01:28:45
            }
### Get all Reservations [GET]

Return a collection of all the reservations for this user.

+ Response 200 (application/json)

        {
            "id": {user_id},
            "published_at": "2016-11-11T08:40:51.620Z",
            "url": "/reservations/{user_id}/{task_id}",
            "reservations": 
            [
                {
                    "id": {task_id},
                    "site":"mySite",
                    "start time": 2016 021 01:27:45,
                    "stop time":2016 021 01:28:45,
                },
                {
                    "id": {task_id},
                    "site":"mySite",
                    "start time": 2016 021 01:27:45,
                    "stop time":2016 021 01:28:45
                }
            ]
        }
### Create a New Reservation [POST]
Requests a new reservation with this action.
This action takes a JSON payload as part of the request.
Response then return specific header and body.

+ Request (application/json)

        {
            "reservation": 
            [
                {
                    "site":"mySite",
                    "start time": 2016 021 01:27:45,
                    "stop time":2016 021 01:28:45
                }
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /reservation/{task_id}

    + Body

            {
                "published_at": "2016-11-11T08:40:51.620Z",
                "url": "/reservation/{task_id}",
                "reservation": 
                [
                    {
                        "site":"mySite",
                        "start time": 2016 021 01:27:45,
                        "stop time":2016 021 01:28:45
                    }
                ]
                   
            }


## Reservation [/reservation/{task_id}]
A reservation request

Required Attribute:
    - user_id
    - 'stationId'
    - 'StartTime'
    - 'StopTime'

    
Option attributes:

    - 'satellite'
    
+ Parameters
    + task_id (number) - ID of the reservation in the form of an integer


### View a Reservation Detail [GET]
Return a reservation detail.

+ Response 200 (application/json)

        {
            "id": {user_id},
            "published_at": "2016-11-11T08:40:51.620Z",
            "url": "/reservation/{task_id}",
            "reservation": 
            [
                {
                    "id": {task_id},
                    "site":"mySite",
                    "start time": 2016 021 01:27:45,
                    "stop time":2016 021 01:28:45,
                },
            ]
        }
        
### Delete [DELETE]
Deletes a specific reservation.

+ Response 204