FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# viaDDSdemo1

viaDDSdemo1 is an ViaSat Data Delivery service API allowing consumers to request data collection from various antenna sites around the world.


## Reservation Collection [/reservations_{user_id}]

A colleciton of all reservations for a particular user

+ Parameters
    + user_id (number) - ID of the dds user in the form of an integer

+ Model (application/json)

    +   Body
    
            {
                "id": {user_id}
                "start time": 2016 021 01:27:45
                "stop time":2016 021 01:28:45
            }


## Reservation [/reservation/{user_id}]

A reservation request

Required Attribute:
    - user_id
    - 'StartTime'
    - 'StopTime'
    
Option attributes:
    - 'stationId'
    - 'satellite'